<?php 

    global $list_pattern_bg;

    $list_pattern_bg = array(

                                '1'=>'ish-solid-wood-dark.jpg',
                                '2'=>'ish-solid-wood-light.jpg',
                                '3'=>'ish-transparent-grid.gif',
                                '4'=>'ish-transparent-stripes-dark.png',
                                '5'=>'ish-transparent-stripes-light.png',
                                '6'=>'ish-transparent-stripes-very-dark.png',
                                '7'=>'solid-dark-black-linen-v2.png',
                                '8'=>'solid-dark-brushed-alu-dark.png',
                                '9'=>'solid-dark-carbon-fibre.png',
                                '10'=>'solid-dark-carbon-fibre-v2.png',
                                '11'=>'solid-dark-criss-cross.png',
                                '12'=>'solid-dark-dark-brick-wall.png',
                                '13'=>'solid-dark-dark-denim.png',
                                '14'=>'solid-dark-dark-leather.png',
                                '15'=>'solid-dark-dark-mosaic.png',
                                '16'=>'solid-dark-dark-wood.png',
                                '17'=>'solid-dark-escheresque_ste.png',
                                '18'=>'solid-dark-fake-brick.png',
                                '19'=>'solid-dark-gun-metal.png',
                                '20'=>'solid-dark-irongrip.png',
                                '21'=>'solid-dark-moulin.png',
                                '22'=>'solid-dark-pixels.png',
                                '23'=>'solid-dark-rubber-grip.png',
                                '24'=>'solid-dark-simple_dashed.png',
                                '25'=>'solid-dark-vertical-cloth.png',
                                '26'=>'solid-light-beige-paper.png',
                                '27'=>'solid-light-bg2.png',
                                '28'=>'solid-light-bg3.png',
                                '29'=>'solid-light-bg4.png',
                                '30'=>'solid-light-bg5.png',
                                '31'=>'solid-light-bg6.jpg',
                                '32'=>'solid-light-bg7.jpg',
                                '33'=>'solid-light-bg8.png',
                                '34'=>'solid-light-bg11.png',
                                '35'=>'solid-light-brushed-alu.png',
                                '36'=>'solid-light-concrete-wall-2.png',
                                '37'=>'solid-light-cream-pixels.png',
                                '38'=>'solid-light-double-lined.png',
                                '39'=>'solid-light-escheresque.png',
                                '40'=>'solid-light-fabric-plaid.png',
                                '41'=>'solid-light-grunge_wall.png',
                                '42'=>'solid-light-noisy.png',
                                '43'=>'solid-light-p5.png',
                                '44'=>'solid-light-paper_1.png',
                                '45'=>'solid-light-paper_2.png',
                                '46'=>'solid-light-paper_3.png',
                                '47'=>'solid-light-pinstripe.png',
                                '48'=>'solid-light-squairy_light.png',
                                '49'=>'solid-light-wood-pattern.png',
                                '50'=>'solid-light-wp-boldial-ahoy.jpg',
                                '51'=>'solid-light-wp-boldial-asteroids.jpg',
                                '52'=>'solid-light-wp-boldial-brijan.gif',
                                '53'=>'solid-light-wp-boldial-cuadros.png',
                                '54'=>'solid-light-wp-boldial-kale-salad.jpg',
                                '55'=>'solid-light-wp-boldial-leather-nunchuck.png',
                                '56'=>'solid-light-wp-boldial-shattered-island.gif',
                                '57'=>'square_bg.png',
                                '58'=>'transparent-bg0.png',
                                '59'=>'transparent-bg1.png',
                                '60'=>'transparent-bg10.png',

                            )

?>